# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Guacamole thanks to PR

on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: Thanks everyone that made PRs
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Thanks for request this pull, we will look as soon as possible!'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
